server:
  port: 8081

# === ??(??/??) ===
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.security: INFO
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.jdbc: INFO
    org.springframework.r2dbc: INFO
    org.springframework.transaction: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: resume-test
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/test-realm
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/postgres
    table: resume_app_schema_history

  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: app_pass
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:app_db}?sslmode=${APP_DB_SSLMODE:disable}
#    username: ${APP_DB_USER:app_user}
#    password: ${APP_DB_PASSWORD:app_pass}
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # ???? validate ??, ??? ??? Flyway/Liquibase ?? ??
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        show_sql: true

#  r2dbc:
#    url: r2dbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:app_db}?sslMode=${APP_DB_SSLMODE:disable}
#    username: ${APP_DB_USER:app_user}
#    password: ${APP_DB_PASSWORD:app_pass}
#    pool:
#      initial-size: ${R2DBC_POOL_INITIAL:5}
#      max-size: ${R2DBC_POOL_MAX:40}
#      max-idle-time: ${R2DBC_POOL_IDLE:PT30S}
#      validation-query: SELECT 1
