services:
  wkhtmltopdf:
    build:
      context: ../
      dockerfile: docker/wkhtmltopdf/Dockerfile
    image: resume-core/wkhtmltopdf:local
    container_name: wkhtmltopdf-cli
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    restart: unless-stopped
    networks:
      - local-net

volumes:
  pgdata:

networks:
  local-net:
    external: true
