services:
  postgres:
    image: postgres:16
    container_name: pg-main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # 아래 init 스크립트 자동 실행

  wkhtmltopdf:
    build:
      context: ../
      dockerfile: docker/wkhtmltopdf/Dockerfile
    image: resume-core/wkhtmltopdf:local
    container_name: wkhtmltopdf-cli
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    restart: unless-stopped
volumes:
  pgdata:
